version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range

  app:
    build: ../local-testing
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - "AWS_ENDPOINT=http://127.0.0.1:4566"
